#!/bin/bash
#
# Script achieves:
#   - Setup mssql components on Linux
#   - Install Python twisted

DB_SERVER=$1
DB_DB=$2
DB_USER=$3
DB_PASSWORD=$4

DATA
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run with root privileges"
    exit 1
fi

apt-get update
apt-get install -y python-pip python-twisted-web2

curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list

apt-get update
export DEBIAN_FRONTEND=noninteractive
export ACCEPT_EULA=y
apt-get install -y mssql-tools unixodbc-dev
pip install pyodbc==3.1.1

mkdir -p /var/lib/sql_twisted

cp sqldb_app.py /var/lib/sql_twisted/
cp sql_twisted.service /etc/systemd/system/

/opt/mssql-tools/bin/sqlcmd -S ${DB_SERVER}.database.windows.net -U ${DB_USER}@${DB_SERVER} -P "${DB_PASSWORD}" -d ${DB_DB} -i initial_db.sql

cat > /var/lib/sql_twisted/config.json <<EOF
{
    "dbuser": "${DB_USER}",
    "dbpasswd": "${DB_PASSWORD}",
    "sqlserver": "${DB_SERVER}.database.windows.net",
    "db": "${DB_DB}"
}
EOF

systemctl start sql_twisted
